server:
  port: 9081

spring:
  application:
    name: consumer-app
  kafka:
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093

    producer:
      bootstrap-servers:
        - localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSeserializer
      value-serializer: org.apache.kafka.common.serialization.StringSeserializer
    template:
      default-topic: library-events

    consumer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-deserializer:  org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: event-listeners-group
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

